### ISSUE TITLE
UFCS issue iterator into macro

### ISSUE THREAD

**Issue by sotolf2** [nim-works/nimskull#1255]
This is kind of difficult for me to explain but it works differently from what I expected and I don't really quite know why

### Example

This example which is what I usually used in nim does not work when trying to read lines from a file into a seq

```nim
import std/[sequtils]
let lines = "filename".lines.to_seq
```

This just brings a type mismatch:

```
day19.nim(16, 25) Error: undeclared field: 'lines' for type system.string [type declared in /home/sotolf/bin/nim-0.1.0-dev.21274/lib/system.nim(34, 3)]
```

I managed to get it working by doing it as follows:

```nim
import std/[sequtils]
let lines = to_seq "filename".lines
```

I'm not quite sure if this is something that is expected, at least in my mind the two examples should generate the same code, unless I'm misunderstanding something. That's the only snag that I hit in my files even though I can be rather sloppy with how I use UFCS, with that line change everything else works like a charm.

**Comment by zerbina** [comment]
At the center of the problem is that for expression `a.b`, `a` is analyzed first, and if there's an error with it, `b(a)` is never attempted. The manual also has an [entry](https://nim-works.github.io/nimskull/manual.html#templates-limitations-of-the-method-call-syntax) regarding this limitation (`toSeq` is a template).

**Edit:** Sorry, I made a mistake reading the compiler debugger output, it's a classic AST corruption issue. The compiler already tries `b(a)` when `a.b` is an error.

Nonetheless, I consider this limitation to be a bug that needs to be fixed.

**Comment by zerbina** [comment]
The only way forward here seems to be always considering `iterator` symbols during overload resolution (they're currently only considered in certain contexts).

**Comment by sotolf2** [comment]
Ah, so from what I've understood, in order to not allow false programs to compile the way to do this at least for the time being is to keep it to the form like this :)

```nim
import std/[sequtils]
let lines = to_seq "filename".lines
```

Thank you for looking into it and dealing with it so quickly, at least now I think I understand why it doesn't work, which is already a good thing :)

**Comment by zerbina** [comment]
> Ah, so from what I've understood, in order to not allow false programs to compile the way to do this at least for the time being is to keep it to the form like this :)

Yep, using the explicit call or command syntax works around the method-call syntax limitation.

In general, `a.b` and `b(a)` are not fully interchangeable, and whether that's going change or stay is not entirely clear at the moment.
