### ISSUE TITLE
replace magic functions with plain functions

### ISSUE THREAD

**Issue by ringabout** [nim-works/nimskull#13]
## abs
https://github.com/timotheecour/Nim/issues/476
https://github.com/timotheecour/Nim/pull/485

## swap (JS backend)
https://github.com/nim-lang/Nim/pull/16778

**Comment by saem** [comment]
A procedural note: Please don't link Tim's PRs as the only body of a ticket. I have no interest trying to decipher his writing style, let alone looking through all the code line by line spotting issues or worse not because of accidental complexity. Tim's style might work great for him or the nim compiler but it's an absolute non-starter for me.

What the title of this issue seems to suggest might be a good idea, but I want to hear about what impacts we expect to see in terms of the current mission.

For example nkError:
- allows us to rework large parts of sem to be linear in control flow and or functions
- separate code into query, judgement, and production
- ease the implementation of IC
- improve error messages

The power to weight ratio is high as you can see, what's it like for magics?

**Comment by saem** [comment]
Guessing this wasn't important since I didn't get a reply.
